---
# The first level of keys are columns in table products. deeper structures are
# preserved as such in the respective column. The processor(the program) must
# load the structure and Dump it to convert it to a hash and then do whatewer
# it is going to do.
- {sku: 9786199169025, alias: лечителката, title: 'Лечителката и рунтавата ѝ котка', p_type: book,
    properties: {
      price: 14.00, weight: 0.300, series: Паралелен свят (първа книга), dimensions: 115×165 мм. (джобен),
      author: Контадин Кременски,
      images: [/img/korica-lechitelkata-96dpi-200x288.webp,],
      button_icon: /css/malka/book-open-page-variant-outline.svg,
      exerpts_url: /books/lechitelkata-otkusi.pdf, variant: книжно издание, in_store: true
    }
  }
- {sku: 9786199169032, alias: лечителката, title: 'PDF Лечителката и рунтавата ѝ котка', p_type: book, 
  properties: {
      price: 9.81, weight: 0.0,
      button_icon: /css/malka/file-pdf-box.svg, 
      exerpts_url: /books/lechitelkata-otkusi.pdf, variant: PDF,in_store: true
      }}

- alias: матере-нашѧ-параскеви
  p_type: book
  properties:
    author: Красимир Беров – съставител
    dimensions: 148×210 мм.(A5)
    exerpts_url: /books/PetkaZograf074-exerpts.pdf
    images: [/img/PetkaZograf074_250x355x96.jpg]
    button_icon: /css/malka/book-open-page-variant-outline.svg
    price: 7.00
    weight: 0.050
    variant: книжно издание
    in_store: true
  sku: 9786199169001
  title: Житие на света Петка Българска от свети патриарх Евтимий

- alias: матере-нашѧ-параскеви
  p_type: book
  properties:
    button_icon: /css/malka/file-pdf-box.svg
    price: 5.00
    weight: 0.0
    variant: PDF
    in_store: true
  sku: 9786199169018 
  title: PDF Житие на света Петка Българска от свети патриарх Евтимий

