---
# The first level of keys are columns in table products. deeper structures are
# preserved as such in the respective column. The processor(the program) must
# load the structure and Dump it to convert it to a hash and then do whatewer
# it is going to do.
- {sku: 9786199169025, alias: лечителката, title: 'Лечителката и рунтавата ѝ… котка', p_type: book,
  properties: {
      price: 15.00, weight: 0.300, series: Паралелен свят (първа книга), dimensions: 115×165 мм. (джобен),
      author: Контадин Кременски,
      images: [/img/korica-lechitelkata-96dpi-200x288.webp,],
      button_icon: /css/malka/book-open-page-variant-outline.svg,
      exerpts_url: /books/lechitelkata-otkusi.pdf, variant: книжно издание,
      }}

- alias: матере-нашѧ-параскеви
  p_type: book
  properties:
    author: Красимир Беров – съставител
    dimensions: 148×210 мм.(A5)
    exerpts_url: /books/PetkaZograf074-exerpts.pdf
    images: [/img/PetkaZograf074_250x355x96.jpg]
    button_icon: /css/malka/book-open-page-variant-outline.svg
    price: 8.00
    weight: 0.050
    variant: книжно издание
  sku: 9786199169001
  title: Житие на света Петка Българска
